export const AI_PROVIDERS = [
  {
    id: 'google-gemini',
    name: 'Google Gemini',
    shortName: 'Gemini',
    color: '#4285F4',
    logoColor: '#4285F4',
    logoUrl: 'https://cdn.simpleicons.org/googlegemini',
    website: 'https://ai.google.dev',
    apiUrl: 'https://generativelanguage.googleapis.com',
    testEndpoint: '/v1/models',
    description: 'Google AI for developers',
  },
  {
    id: 'openai',
    name: 'OpenAI',
    shortName: 'OpenAI',
    color: '#10A37F',
    logoColor: '#10A37F',
    logoUrl: 'https://www.google.com/s2/favicons?domain=openai.com&sz=128',
    website: 'https://platform.openai.com',
    apiUrl: 'https://api.openai.com',
    testEndpoint: '/v1/models',
    description: 'GPT, DALL·E, and more',
  },
  {
    id: 'anthropic',
    name: 'Anthropic Claude',
    shortName: 'Claude',
    color: '#D97706',
    logoColor: '#D97706',
    logoUrl: 'https://www.google.com/s2/favicons?domain=anthropic.com&sz=128',
    website: 'https://console.anthropic.com',
    apiUrl: 'https://api.anthropic.com',
    testEndpoint: '/v1/messages',
    description: 'Claude AI assistant',
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    shortName: 'DeepSeek',
    color: '#4F46E5',
    logoColor: '#4F46E5',
    logoUrl: 'https://www.google.com/s2/favicons?domain=deepseek.com&sz=128',
    website: 'https://platform.deepseek.com',
    apiUrl: 'https://api.deepseek.com',
    testEndpoint: '/v1/models',
    description: 'DeepSeek AI models',
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    shortName: 'OpenRouter',
    color: '#6366F1',
    logoColor: '#6366F1',
    logoUrl: 'https://www.google.com/s2/favicons?domain=openrouter.ai&sz=128',
    website: 'https://openrouter.ai',
    apiUrl: 'https://openrouter.ai/api',
    testEndpoint: '/v1/models',
    description: 'Multi-model API gateway',
  },
  {
    id: 'groq',
    name: 'Groq',
    shortName: 'Groq',
    color: '#F97316',
    logoColor: '#F97316',
    logoUrl: 'https://www.google.com/s2/favicons?domain=groq.com&sz=128',
    website: 'https://console.groq.com',
    apiUrl: 'https://api.groq.com',
    testEndpoint: '/openai/v1/models',
    description: 'Ultra-fast AI inference',
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    shortName: 'Mistral',
    color: '#FF7000',
    logoColor: '#FF7000',
    logoUrl: 'https://www.google.com/s2/favicons?domain=mistral.ai&sz=128',
    website: 'https://console.mistral.ai',
    apiUrl: 'https://api.mistral.ai',
    testEndpoint: '/v1/models',
    description: 'Open-weight AI models',
  },
  {
    id: 'xai',
    name: 'xAI (Grok)',
    shortName: 'xAI',
    color: '#1DA1F2',
    logoColor: '#1DA1F2',
    logoUrl: 'https://www.google.com/s2/favicons?domain=x.ai&sz=128',
    website: 'https://console.x.ai',
    apiUrl: 'https://api.x.ai',
    testEndpoint: '/v1/models',
    description: 'Grok AI by xAI',
  },
  {
    id: 'cohere',
    name: 'Cohere',
    shortName: 'Cohere',
    color: '#39D98A',
    logoColor: '#39D98A',
    logoUrl: 'https://www.google.com/s2/favicons?domain=cohere.com&sz=128',
    website: 'https://dashboard.cohere.com',
    apiUrl: 'https://api.cohere.com',
    testEndpoint: '/v1/models',
    description: 'Enterprise AI platform',
  },
  {
    id: 'huggingface',
    name: 'Hugging Face',
    shortName: 'HuggingFace',
    color: '#FFD21E',
    logoColor: '#FFD21E',
    logoUrl: 'https://www.google.com/s2/favicons?domain=huggingface.co&sz=128',
    website: 'https://huggingface.co/settings/tokens',
    apiUrl: 'https://api-inference.huggingface.co',
    testEndpoint: '/models',
    description: 'Open-source AI models',
  },
  {
    id: 'replicate',
    name: 'Replicate',
    shortName: 'Replicate',
    color: '#3B82F6',
    logoColor: '#3B82F6',
    logoUrl: 'https://www.google.com/s2/favicons?domain=replicate.com&sz=128',
    website: 'https://replicate.com',
    apiUrl: 'https://api.replicate.com',
    testEndpoint: '/v1/models',
    description: 'Run open-source models',
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    shortName: 'Perplexity',
    color: '#20B2AA',
    logoColor: '#20B2AA',
    logoUrl: 'https://www.google.com/s2/favicons?domain=perplexity.ai&sz=128',
    website: 'https://www.perplexity.ai/settings/api',
    apiUrl: 'https://api.perplexity.ai',
    testEndpoint: '/chat/completions',
    description: 'AI-powered search',
  },
];

export const getProviderById = (id) => {
  return AI_PROVIDERS.find(p => p.id === id);
};

export const getProviderByName = (name) => {
  return AI_PROVIDERS.find(p => p.name.toLowerCase() === name.toLowerCase());
};
